version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_pass
      POSTGRES_DB: shop_db
    ports:
      - '5432:5432'
  server:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://example_user:example_pass@db:5432/shop_db
